//generated by generate_images.py

const outfit_list = ["Shirt",];
const body_list = ["Torso","Head",];
const expression_list = ["Eyes","Eyebrows","Mouth",];

const skin_list = ["Torso","Head","Eyebrows",];
const hair_list = ["Hair_back","Hair_middle","Hair_front","Facial_hair",];

const head_list = ["medium","round",];
const torso_list = ["medium",];
const eyebrow_list = ["none","flat_thick",];
const shirt_list = ["none","shirt",];

const skinNum = 2; //how many skin colours there are
