//generated by generate_images.py

const outfit_list = ["Shirt","Accessory","Coat","Eyewear","Hat",];
const body_list = ["Torso","Head","Complexion","Ears","Nose",];
const expression_list = ["Eyes","Eyebrows","Mouth",];

const skin_list = ["Torso","Head","Complexion","Ears","Nose",];
const hair_list = ["Hair_back","Hair_middle","Hair_front","Facial_hair",];

const skinNum = 2; //how many skin colours there are
full_body_list = body_list+hair_list;

const coat_back_list = ["none","cardigan",];
const hat_back_list = ["none","straw",];
const hair_back_list = ["none","short",];
const ears_list = ["regular",];
const torso_list = ["medium",];
const head_list = ["medium","round",];
const eye_list = ["medium",];
const mouth_list = ["flat",];
const eyebrow_list = ["none","flat_thick",];
const nose_list = ["none","medium",];
const shirt_list = ["none","shirt",];
const coat_list = ["none","cardigan",];
const facial_hair_list = ["none","mo",];
const hair_middle_list = ["none","sidepart",];
const hair_front_list = ["none","emo",];
const hat_list = ["none","straw",];

add_item("Hair_back",hair_back_list)
add_item("Ears",ears_list)
add_item("Torso",torso_list)
add_item("Head",head_list)
add_item("Eyes",eye_list)
add_item("Mouth",mouth_list)
add_item("Eyebrows",eyebrow_list)
add_item("Nose",nose_list)
add_item("Shirt",shirt_list)
add_item("Coat",coat_list)
add_item("Facial_hair",facial_hair_list)
add_item("Hair_middle",hair_middle_list)
add_item("Hair_front",hair_front_list)
add_item("Hat",hat_list)

