//generated by generate_images.py

const outfit_list_both = ["Neckwear","Eyewear","Earrings","Hat",];
const outfit_list_complex = ["Shirt","Coat",];
const outfit_list_portOnly = [];
const outfit_list_spriteOnly = ["Pants","Shoes","Gloves",];
const outfit_list = outfit_list_both.concat(outfit_list_spriteOnly).concat(outfit_list_portOnly);
const body_list = ["Torso","Head","Complexion","Ears","Nose","Nose_front",];
const skin_list = ["Torso","Head","Complexion","Ears","Nose","Nose_front","Eyebrows","Mouth",];
const hair_list = ["Hair_back","Hair_middle","Hair_front","Facial_hair",];
const expression_list = ["Eyes","Eyebrows","Mouth",];

const eye_colours = ["#000000","#B25DF6","#1B8EF6","#469951","#F0B50A",];
const outfit_yellow = ["#FFE201","#FF9F02","#FFDBB6","#F7BE4F",];
const outfit_green = ["#73D080","#4F8B20","#8CC54E","#277032","#56AA04","#7CA838",];
const outfit_blue = ["#477BC8","#3C92ED","#1FDBFF","#2E4D91",];
const outfit_purple = ["#BF2C92","#D361A7","#A46FE2","#9431C6",];
const outfit_red = ["#F0303C","#B71B00","#E55773",];
const outfit_brown = ["#B24836","#912D20","#820000","#630F0F",];
const outfit_grey = ["#FFFFFF","#777471","#4C4C56","#482B57","#000000",];
const outfit_colours = outfit_yellow.concat(outfit_green,outfit_blue,outfit_purple,outfit_red,outfit_brown,outfit_grey,);
const skin_regular = ["#FFE7D6","#FFD3A6","#FFD3A6","#FFDFA5","#F1A065","#DA773F","#DA874A","#B05934","#B96A2E","#853F27","#783F1A",];
const skin_weird = ["#C3FFFA","#41AD60","#000000","#9BB681",];
const skin_colours = skin_regular.concat(skin_weird,);
const hair_weird = ["#7034ED","#B25DF6","#1B8EF6","#53C7FB","#469951",];
const hair_grey = ["#A59A9D","#E9E9E9",];
const hair_blonde = ["#FCE374","#F0B50A",];
const hair_red = ["#FE7423","#FF5565","#DF433C","#D16132",];
const hair_brown = ["#641D00","#923D1F","#8B4910","#BB742E",];
const hair_black = ["#48356E","#4B261E","#5B483C","#5A5A7F","#602372","#000000",];
const hair_colours = hair_blonde.concat(hair_red,hair_brown,hair_black,hair_weird,hair_grey,);

const colourlist_list = [["yellow",outfit_yellow],["green",outfit_green],["blue",outfit_blue],["purple",outfit_purple],["red",outfit_red],["brown",outfit_brown],["grey",outfit_grey],["regular",skin_regular],["weird",skin_weird],["blonde",hair_blonde],["red",hair_red],["brown",hair_brown],["black",hair_black],["weird",hair_weird],["grey",hair_grey],];

const skinNum = 15; //how many skin colours there are
const eyeNum = 5; //how many eye colours there are
const hairNum = 23; //how many hair colours there are
const outfitNum = 30; //how many clothing colours there are
const full_body_list = body_list+hair_list;

const coat_back_list = ["none","suit jacket","jacket","hoodie",];
const hat_back_list = ["none","straw",];
const hair_back_list = ["none","short",];
const ears_list = ["regular",];
const torso_list = ["medium",];
const head_list = ["square","medium","round",];
const complexion_list = ["none","wrinkles",];
const nose_list = ["none","button","medium","broad","round","pointed",];
const eyebrow_list = ["none","flat_thick",];
const eye_list = ["medium",];
const mouth_list = ["flat",];
const earrings_list_port = ["none","studs",];
const shirt_list_port = ["none","button up","tshirt",];
const neckwear_list_port = ["none","tie",];
const shirt_collar_list = ["none","button up",];
const coat_list_port = ["none","suit jacket","jacket","hoodie",];
const facial_hair_list_port = ["none","beard","moustache","big moustache","goatee","soul patch","fluffy goatee",];
const eyewear_list_port = ["none","glasses","half-glasses","shiny glasses","robot visor","sunglasses","eye-patch",];
const hair_middle_list = ["none","sidepart",];
const hair_front_list = ["none","emo",];
const hat_list_port = ["none","straw",];

add_portrait_object("Coat_back",coat_back_list)
add_portrait_object("Hat_back",hat_back_list)
add_portrait_object("Hair_back",hair_back_list)
add_portrait_object("Ears",ears_list)
add_portrait_object("Torso",torso_list)
add_portrait_object("Head",head_list)
add_portrait_object("Complexion",complexion_list)
add_portrait_object("Nose",nose_list)
add_portrait_object("Eyebrows",eyebrow_list)
add_portrait_object("Eyes",eye_list)
add_portrait_object("Mouth",mouth_list)
add_portrait_object("Earrings",earrings_list_port)
add_portrait_object("Shirt",shirt_list_port)
add_portrait_object("Neckwear",neckwear_list_port)
add_portrait_object("Shirt_collar",shirt_collar_list)
add_portrait_object("Coat",coat_list_port)
add_portrait_object("Facial_hair",facial_hair_list_port)
add_portrait_object("Nose_front",nose_list)
add_portrait_object("Eyewear",eyewear_list_port)
add_portrait_object("Hair_middle",hair_middle_list)
add_portrait_object("Hair_front",hair_front_list)
add_portrait_object("Hat",hat_list_port)

const facial_hair_list_sprite = ["none","beard","moustache","big moustache","goatee","soul patch","fluffy goatee",];
const facial_hair_list_menu = ["none","beard","moustache","big moustache","goatee","soul patch","fluffy goatee",];
const hat_list_sprite = ["cowboy hat","Bowler","Top hat","sombrero","straw hat","official cap","blue bonnet","Chapeau","Skeleton mask","Goblin Mask","Chicken Mask","Earmuffs","Delicate Bow","Tropiclip","Butterfly Bow","Hunter's Cap","Trucker Hat","Sailor's Cap","Good Ol' Cap","Fedora","Cool Cap","Lucky Bow","Polka Bow","Gnome's Cap","Eye Patch","Santa Hat","Tiara","Hard Hat","Sou'wester","Daisy","Watermelon Band","Mouse Ears","Cat Ears","Cowgal Hat","Cowpoke Hat","Archer's Cap","Panda Hat","Blue Cowboy Hat","Red Cowboy Hat","Cone Hat","Living Hat","Emily's Magic Hat","Mushroom Cap","Dinosaur Hat","Totem Mask","Logo Cap","Dwarf Helm","Fashion Hat","Pumpkin Mask","Hair Bone",];
const hat_list_menu = ["none","straw",];
const shirt_list_menu = ["none","button up",];
const neckwear_list_sprite = ["bandana","necklace","bow-tie","tie","choker",];
const neckwear_list_menu = ["none","tie",];
const coat_list_sprite = ["none","suit jacket","jacket","hoodie",];
const coat_list_menu = ["none","suit jacket","jacket","hoodie",];
const eyewear_list_sprite = ["glasses","half-glasses","shiny glasses","robot visor","sunglasses","eye-patch",];
const eyewearlist_menu = ["glasses","half-glasses","shiny glasses","robot visor","sunglasses","eye-patch",];
const earrings_list_sprite = ["gold drop","blue drop","studs","single stud",];
const earrings_list_menu = ["none","studs",];

